server:
  port: 8888
  servlet:
    context-path: /config-server

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #uri: file:///GITBB//microservices//git-config-repo
          uri: https://github.com/WillianCahuaya/microservices.git
          default-label: develop
          searchPaths: /git-config-repo
          timeout: 4
          username: wcahuayaramos@gmail.com
          password: noseusa